### ISSUE TITLE
are CraftTweaker supported?

### ISSUE THREAD

**Issue by vitaluska123** [val-int1/bigger_craft#2]
поддерживается ли создание крафтов через CraftTweaker?

**Comment by val-int1** [comment]
I don't know, as I didn't even think CraftTweaker existed for version beyond 1.13 (when they added recipes in datapacks).
But since the mod modifies the vanilla shaped/shapeless recipe types, it might work (unless CraftTweaker also has a size check). Though that was causing more issues than it was solving, so the next version of the mod will have it's own recipe types, and I'll check to see if CraftTweaker works out of the box with those.

Also, slight nitpick, but I would prefer if issues were about actual problems, and not just questions (I should make that clear in the mod page I guess lol).
