### ISSUE TITLE
REI Support?

### ISSUE THREAD

**Issue by UnicornMaster-dev** [val-int1/bigger_craft#5]
In the Q&A, it mentions that REI Support will be fixed. Is this still happening?

**Comment by val-int1** [comment]
Yes, though I had to make a custom recipe type instead of "hijacking" the vanilla one because REI hardcodes everything vanilla related :/ But that's pretty easy to fix, all that's needed is to change the recipe type to `bigger_craft:big_crafting_shaped` or `bigger_craft:big_crafting_shapeless`, everything else is exactly the same.
Also the next update is basically complete, I was sidetracked with another little Minecraft mod.
